project:
  type: book
  output-dir: docs

book:
  title: "Quantitative Finance Lab"
  author: "Ramtin Asadi"
  chapters:
    - index.qmd
    - overview.qmd
    - notebooks/01_yield_curve_bond_pricing_and_risk.ipynb
    - notebooks/02_portfolio_optimization_MV_models.ipynb
    - notebooks/03_risk_report_engine_and_CAPM.ipynb
    - notebooks/04_BSM_IV_greeks_hedging.ipynb
    - notebooks/05_GARCH_forecasting_VRP.ipynb
    - notebooks/06_portfolio_black_littreman.ipynb
    - notebooks/07_dynamic_hedge_ratios.ipynb
    - notebooks/08_vol_surface_local_vol.ipynb
    - notebooks/09_term_structure_models.ipynb

format:
  html:
    theme: flatly
    toc: false
    number-sections: false


