repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(quantfinlab|tests)/.*\.pyi?$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        files: ^(quantfinlab|tests)/.*\.pyi?$
      - id: trailing-whitespace
        files: ^(quantfinlab|tests)/.*\.pyi?$
