from __future__ import annotations

from . import (
    attribution,
    black_litterman,
    confidence,
    constraints,
    costs,
    covariance,
    cvar,
    expected_returns,
    hrp,
    optimizers,
    risk_parity,
    robust,
    selection,
    sizing,
    universe,
    views,
)
from .attribution import concentration, effective_number_of_holdings, max_weight, risk_contribution
from .constraints import constraints_feasible, long_only_box_constraints, normalize_weights
from .costs import apply_transaction_costs, portfolio_turnover, transaction_cost_from_turnover
from .covariance import (
    cov_estimate,
    estimate_covariance,
    ewma_covariance,
    ledoit_wolf_covariance,
    make_psd,
    oas_covariance,
    sample_covariance,
)
from .cvar import (
    cvar_budget_path,
    historical_cvar_loss,
    mean_cvar_weight_frame,
    mean_cvar_weights,
    min_cvar_weight_frame,
    min_cvar_weights,
    portfolio_cvar_loss,
)
from .expected_returns import (
    bayes_stein_momentum_mu,
    bayes_stein_mu,
    build_mu_excess_ann,
    build_scaled_mu_from_raw,
    momentum_mu,
    momentum_score_from_returns,
    mu_diagnostics,
    mu_momentum,
    scale_mu_to_target_sharpe,
    winsorize_signal,
    zscore_signal,
)
from .hrp import (
    cluster_labels,
    cluster_membership_table,
    corr_to_distance,
    hrp_weight_frame,
    hrp_weights,
    nco_mv_weight_frame,
    nco_mv_weights,
)
from .optimizers import (
    equal_weight,
    max_sharpe_frontier_grid,
    max_sharpe_slsqp,
    mean_variance,
    minimum_variance,
    ridge_mean_variance,
    weights_equal,
    weights_maxsharpe_frontier_grid,
    weights_maxsharpe_slsqp,
    weights_minvar,
    weights_mv,
    weights_ridge_mv,
)
from .risk_parity import (
    equal_risk_contribution_weights,
    risk_contribution_table,
    risk_contributions,
    risk_parity_weight_frame,
)
from .robust import (
    box_robust_mv_weights,
    box_robust_weight_frame,
    ellipsoid_robust_mv_weights,
    ellipsoid_robust_weight_frame,
    psd_sqrt,
    robust_radius_path,
    robust_weight_frames,
    wasserstein_drmv_weights,
    wasserstein_weight_frame,
)
from .selection import (
    best_strategy_by_sharpe,
    calc_drawdown,
    performance_metrics,
    result_sharpe,
    summarize_results,
)
from .sizing import (
    align_weight_frame,
    cap_weights,
    forecast_gated_maxsharpe_weight_frame,
    forecast_kelly_weight_frame,
    gated_blend_weight_frame,
    kelly_weight_vector,
    normalize_long_only,
    rank_signal_weight_frame,
    smooth_weights,
    weights_from_forecasts,
)
from .universe import (
    build_liquid_universe_by_date,
    clean_close_volume_panels,
    make_rebalance_dates,
    prices_to_returns,
    select_liquid_universe,
)


def backtest(*args, **kwargs):
    from quantfinlab.backtest.portfolio import run_rebalanced_portfolio_backtest

    return run_rebalanced_portfolio_backtest(*args, **kwargs)


def run_rebalanced_portfolio_backtest(*args, **kwargs):
    from quantfinlab.backtest.portfolio import run_rebalanced_portfolio_backtest as _run

    return _run(*args, **kwargs)

DEFAULT_ANNUALIZATION = covariance.DEFAULT_ANNUALIZATION
DEFAULT_SOLVER_ORDER = optimizers.DEFAULT_SOLVER_ORDER

__all__ = [
    "DEFAULT_ANNUALIZATION",
    "DEFAULT_SOLVER_ORDER",
    "apply_transaction_costs",
    "attribution",
    "backtest",
    "bayes_stein_momentum_mu",
    "bayes_stein_mu",
    "best_strategy_by_sharpe",
    "black_litterman",
    "build_liquid_universe_by_date",
    "build_mu_excess_ann",
    "build_scaled_mu_from_raw",
    "calc_drawdown",
    "align_weight_frame",
    "cap_weights",
    "clean_close_volume_panels",
    "confidence",
    "concentration",
    "constraints",
    "constraints_feasible",
    "costs",
    "cov_estimate",
    "covariance",
    "cluster_labels",
    "cluster_membership_table",
    "corr_to_distance",
    "cvar",
    "cvar_budget_path",
    "effective_number_of_holdings",
    "equal_risk_contribution_weights",
    "equal_weight",
    "estimate_covariance",
    "ewma_covariance",
    "expected_returns",
    "forecast_gated_maxsharpe_weight_frame",
    "forecast_kelly_weight_frame",
    "gated_blend_weight_frame",
    "box_robust_mv_weights",
    "box_robust_weight_frame",
    "ellipsoid_robust_mv_weights",
    "ellipsoid_robust_weight_frame",
    "historical_cvar_loss",
    "hrp",
    "hrp_weight_frame",
    "hrp_weights",
    "ledoit_wolf_covariance",
    "long_only_box_constraints",
    "make_psd",
    "make_rebalance_dates",
    "mean_cvar_weight_frame",
    "mean_cvar_weights",
    "max_sharpe_frontier_grid",
    "max_sharpe_slsqp",
    "max_weight",
    "mean_variance",
    "minimum_variance",
    "min_cvar_weight_frame",
    "min_cvar_weights",
    "momentum_mu",
    "momentum_score_from_returns",
    "mu_diagnostics",
    "mu_momentum",
    "nco_mv_weight_frame",
    "nco_mv_weights",
    "kelly_weight_vector",
    "normalize_weights",
    "normalize_long_only",
    "oas_covariance",
    "optimizers",
    "performance_metrics",
    "portfolio_turnover",
    "portfolio_cvar_loss",
    "prices_to_returns",
    "psd_sqrt",
    "result_sharpe",
    "ridge_mean_variance",
    "risk_contribution_table",
    "risk_contributions",
    "risk_contribution",
    "risk_parity",
    "risk_parity_weight_frame",
    "rank_signal_weight_frame",
    "robust",
    "robust_radius_path",
    "robust_weight_frames",
    "run_rebalanced_portfolio_backtest",
    "sample_covariance",
    "scale_mu_to_target_sharpe",
    "select_liquid_universe",
    "selection",
    "sizing",
    "smooth_weights",
    "summarize_results",
    "transaction_cost_from_turnover",
    "universe",
    "views",
    "walkforward",
    "wasserstein_drmv_weights",
    "wasserstein_weight_frame",
    "weights_equal",
    "weights_from_forecasts",
    "weights_maxsharpe_frontier_grid",
    "weights_maxsharpe_slsqp",
    "weights_minvar",
    "weights_mv",
    "weights_ridge_mv",
    "winsorize_signal",
    "zscore_signal",
]
